markdown: rdiscount
permalink: /:title/
url: http://crazycodeman.github.io
name: BlakeKing
author: BlakeKing
qq: 271231406
email: 271231406@qq.com
github: CrazyCodeMan
pygments: true
safe: true
paginate: 15
about: "BlakeKing's Blog"
